version: "3.9"

services:
  nllb-translator:
    build: .
    container_name: nllb-translator
    ports:
      - "8085:8085"
    restart: always
    volumes:
      - hf_cache:/root/.cache/huggingface

volumes:
  hf_cache:
