version: "3.9"

services:
  nllb-distilled-translator:
    build: .
    container_name: nllb-distilled-translator
    ports:
      - "8085:8085"
    restart: unless-stopped
    environment:
      - MODEL_NAME=facebook/nllb-200-distilled-1.3B
    volumes:
      - hf_cache:/root/.cache/huggingface

volumes:
  hf_cache:

