version: '3.8'

services:
  app:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=production
    volumes:
      - model_cache:/root/.cache/huggingface
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

volumes:
  model_cache:
    driver: local
